### ISSUE TITLE
Functions do not highlight! 

### ISSUE THREAD

**Issue by xDGameStudios** [LiarOnce/gml-support#1]
syntax does not highlight, like builtin functions/variables
What do you mean by.... "may require theme support".. do I have to install anything else?
I am on a MAC OSX, can this be the problem?

**Comment by LiarOnce** [comment]
No, you don't need.
"May require theme support" means that the code highlight feature may need to temporarily switch the theme implementation.You can change a theme and then switch back.

**Comment by xDGameStudios** [comment]
How can I do that, to what theme should I change?! Just need to change it.. no matter to what

**Comment by LiarOnce** [comment]
You can refer to this GIF image.
![gml](https://ooo.0o0.ooo/2017/03/22/58d28509c2a0e.gif)
